const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch();
 const page=await browser.newPage();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 page.on('dialog',dialog=>dialog.accept());
 await page.goto('http://127.0.0.1:8765/investigation.html');
 await page.waitForFunction(()=>!document.getElementById('fish').disabled);
 const five=page.frameLocator('iframe[title="5 Whys workspace"]');
 const fish=page.frameLocator('iframe[title="Fishbone workspace"]');
 await five.locator('#problemInput').fill('Delivery delay');
 await five.locator('[data-pm-text="0"]').pressSequentially('Observed evidence');
 await page.locator('#fish').click();
 assert.equal(await fish.locator('[data-pm-text="0"]').inputValue(),'Observed evidence');
 await fish.locator('#fbEffect').fill('Late shipment');
 await page.locator('#five').click();
 assert.equal(await five.locator('#problemInput').inputValue(),'Delivery delay');
 assert.equal(await page.evaluate(()=>localStorage.length),0);
 await page.locator('#mode').click();
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('problem-me:investigation:pilot:v2')));
 assert.equal(saved.toolData['5-whys'].problem,'Delivery delay');
 assert.equal(saved.toolData.fishbone.effect,'Late shipment');
 const before=await page.evaluate(()=>JSON.stringify(localStorage));
 await page.locator('#mode').click();
 await five.locator('#problemInput').fill('Private edit');
 await page.locator('#fish').click();
 assert.equal(await page.evaluate(()=>JSON.stringify(localStorage)),before);
 await page.reload();
 await page.waitForFunction(()=>!document.getElementById('open').disabled);
 await page.locator('#open').click();
 await page.locator('#five').click();
 assert.equal(await five.locator('#problemInput').inputValue(),'Delivery delay');
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('Browser workflow passed. Also review mobile layout and Print/PDF visually.');
})().catch(error=>{console.error(error);process.exitCode=1});
